/*
 * HostPropertyDialog.java
 *
 * Created on 2007/1/26, PM 1:23
 */

package dataprotect.ui;

import dataprotect.cmdp.entity.PPProfileItem;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;
import mylib.UI.*;
import dataprotect.data.*;
import dataprotect.res.*;
        
/**
 *
 * @author  Administrator
 */
public class HostPropertyDialog extends javax.swing.JDialog {
    
    /** Creates new form HostPropertyDialog */
    public HostPropertyDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public HostPropertyDialog( SanBootView view,BootHost host,HashMap map ){
        this( view,true );
        myInit( view,host,map );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel2.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 1, 2, 1)));
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("File System", jPanel1);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Service", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setDisabledTextColor(java.awt.Color.black);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Network Info.", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jTextArea2.setEditable(false);
        jTextArea2.setDisabledTextColor(java.awt.Color.black);
        jScrollPane4.setViewportView(jTextArea2);

        jPanel5.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Partition Info.", jPanel5);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HostPropertyDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    ////GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    ////GEN-END:variables
  
    SanBootView view;
    BootHost host;
    GeneralEditableTable table  = new GeneralEditableTable();
    GeneralEditableTable table1 = new GeneralEditableTable();
    
    private void myInit( SanBootView _view,BootHost _host,HashMap map ){
        view = _view;
        host = _host;
        
        jScrollPane1.getViewport().add( table,null );
        jScrollPane1.getViewport().setBackground( Color.white );
        
        jScrollPane2.getViewport().add( table1,null );
        jScrollPane2.getViewport().setBackground( Color.white );
        
        setupLanguage();
        
        setupVolTable();
        setupServTable( map );
        setupNetworkInfo();
        setupPartitionInfo();
    }
    
    private void setupLanguage(){
        setTitle( SanBootView.res.getString("HostPropertyDialog.title"));
        int index = jTabbedPane1.indexOfComponent( jPanel1 );
        jTabbedPane1.setTitleAt( index, 
            SanBootView.res.getString("HostPropertyDialog.label.targetVol")
        );
        index = jTabbedPane1.indexOfComponent( jPanel3 );
        jTabbedPane1.setTitleAt( index, 
            SanBootView.res.getString("HostPropertyDialog.label.service")
        );
        index = jTabbedPane1.indexOfComponent( jPanel4 );
        jTabbedPane1.setTitleAt( index, 
            SanBootView.res.getString("HostPropertyDialog.label.network")
        );
        index =  jTabbedPane1.indexOfComponent( jPanel5 );
        jTabbedPane1.setTitleAt( index, 
            SanBootView.res.getString("HostPropertyDialog.label.partition")
        );
        jButton1.setText( SanBootView.res.getString("common.button.close"));
    }
    
    private void  setupVolTable(){
        int i,tid,vtid,colSize;
        String crttime;
        Object[][] data;

        colSize = 6;
        Vector list = view.initor.mdb.getVolMapOnClntID( host.getID() );
        int num = list.size();
        
        data = new Object[2+num][colSize];
        data[0][0] = "" + num;      // row num
        data[0][1] = "" + colSize;  // col num
        
        data[1][0] =  SanBootView.res.getString("View.table.volmap.fs");
        data[1][1] =  SanBootView.res.getString("View.table.volmap.name");
        data[1][2] =  SanBootView.res.getString("View.table.volmap.targetid");  
        data[1][3] =  SanBootView.res.getString("View.table.volmap.maxSnap");
        data[1][4] =  SanBootView.res.getString("View.table.volmap.selBootVer");
        data[1][5] =  SanBootView.res.getString("View.table.volmap.bootVer");
        
        for( i=0; i<num; i++ ){
            VolumeMap volMap = (VolumeMap)list.elementAt( i );
            tid = volMap.getVolTargetID();
            data[2+i][0] = volMap;
            data[2+i][1] = volMap.getVolName();
            data[2+i][2] = tid + "";
            if( host.isMTPPProtect() || volMap.isMtppProtect() ){
                data[2+i][3] = volMap.getMaxSnapNum()+"";
            }else{
                MirrorGrp mg = view.initor.mdb.getMGFromVectorOnRootID( volMap.getVol_rootid() );
                if( mg != null ){
                    data[2+i][3] = mg.getMg_max_snapshot()+"";
                }else{
                    data[2+i][3] = "";
                }
            }
            
            vtid = volMap.getVol_last_sel_boot_version();
            if( vtid == -1 || vtid == 0 ){
                data[2+i][4] = SanBootView.res.getString("common.noprotected");
            }else{
                if( vtid == tid ){
                    data[2+i][4] = SanBootView.res.getString("common.vol") + ":" + tid;
                }else{
                    crttime = BasicVDisk.getCreateTimeStr( volMap.getVol_last_sel_boot_info() );
                    if( volMap.isCloneDiskForLastSelBoot() ){
                        if( crttime.length() != 0 ){
                            data[2+i][4] = SanBootView.res.getString("common.cdisk") + ":" + vtid + " [" + crttime + "]";
                        }else{
                            data[2+i][4] = SanBootView.res.getString("common.cdisk") + ":" + vtid;
                        }
                    }else{
                        if( crttime.length() != 0 ){
                            data[2+i][4] = SanBootView.res.getString("common.view") + ":" + vtid + " [" + crttime + "]";
                        }else{
                            data[2+i][4] = SanBootView.res.getString("common.view") + ":" + vtid;
                        }
                    }
                }
            }

            vtid = volMap.getVol_view_targetid();
            if( vtid == -1 || vtid == 0 ){
                data[2+i][5] = SanBootView.res.getString("common.noprotected");
            }else{
                if( vtid == tid ){
                    data[2+i][5] = SanBootView.res.getString("common.vol") + ":" + tid;
                }else{
                    crttime = BasicVDisk.getCreateTimeStr( volMap.getLastGoodBootInfo() );
                    if( volMap.isCloneDiskForLastGoodBoot() ){
                        if( crttime.length() != 0 ){
                            data[2+i][5] = SanBootView.res.getString("common.cdisk") + ":" + vtid + " [" + crttime + "]";
                        }else{
                            data[2+i][5] = SanBootView.res.getString("common.cdisk") + ":" + vtid;
                        }
                    }else{
                        if( crttime.length() != 0 ){
                            data[2+i][5] = SanBootView.res.getString("common.view") + ":" + vtid + " [" + crttime + "]";
                        }else{
                            data[2+i][5] = SanBootView.res.getString("common.view") + ":" + vtid;
                        }
                    }
                }
            }
        }
        
        table.setTableModel( data );
        table.setDefaultLook();

        TableColumnModel tableColumnModel = table.getColumnModel();
        int colNum = tableColumnModel.getColumnCount();
        for( i=0;i<colNum;i++ ){
            tableColumnModel.getColumn(i).setCellRenderer(new BrowserTableCellRenderer());
        }

        tableColumnModel.getColumn(0).setWidth( 70 );
        tableColumnModel.getColumn(1).setWidth( 75 );
        tableColumnModel.getColumn(2).setWidth( 55 );
        tableColumnModel.getColumn(3).setWidth( 70 );
        tableColumnModel.getColumn(4).setWidth( 225 );
        tableColumnModel.getColumn(5).setWidth( 225 );
        for( i=0; i<colNum; i++ )
            table.sizeColumnsToFit(i);

        table.getTableHeader().setBorder( BorderFactory.createRaisedBevelBorder() );
        table.getTableHeader().setReorderingAllowed(false);
    }

    private void setupServTable( HashMap map ){
        if( host.isMTPPProtect() ){
            setupServTableForMTPP();
        }else{
            setupServTableForCMDP( map );
        }
    }
    
    private HashMap getServiceForCMDP( HashMap map ){
        ArrayList<PPProfileItem> itemList = view.initor.mdb.getPPProfileItem( host.getID() );
        HashMap<String,Service> ret = new HashMap<String,Service>();

        int size = itemList.size();
        for( int i=0; i<size; i++ ){
            PPProfileItem item = itemList.get(i);
            String[] sList = item.getVolMap().getServices();
            for( int j=0; j<sList.length; j++ ){
                if( sList[j].length() == 0 ) continue;

                Object serv = map.get( sList[j] );
                if( serv != null ){
                    if( ret.get( sList[j]) == null ){
                        Service servObj = (Service)serv;
                        ret.put( sList[j], servObj );
                    }
                }
            }
        }
        return ret;
    }
    
    private void setupServTableForCMDP( HashMap map ){
        Object[][] data;
        
        HashMap list = this.getServiceForCMDP( map );
        Set keySet = list.keySet();
        Iterator iterator = keySet.iterator();
        int num = keySet.size();

        data = new Object[2+num][2]; //name,desc
        data[0][0] = "" + num;    // row num
        data[0][1] = "" + 2;      // col num

        data[1][0] = SanBootView.res.getString("SelectServicePane.table.service.name");
        data[1][1] = SanBootView.res.getString("SelectServicePane.table.service.desc");
        
        int i=0;
        while( iterator.hasNext() ){
            String key = (String)iterator.next();
            Service serv = (Service)list.get( key );
            data[2+i][0] = serv.getServName();
            data[2+i][1] = serv.getServDesc();
            i++;
        }

        table1.setTableModel( data );
        table1.setDefaultLook();

        TableColumnModel tableColumnModel = table1.getColumnModel();
        int colNum = tableColumnModel.getColumnCount();
        for( i=0;i<colNum;i++ ){
            tableColumnModel.getColumn(i).setCellRenderer(new BrowserTableCellRenderer());
        }

        tableColumnModel.getColumn(0).setWidth( 150 );
        tableColumnModel.getColumn(1).setWidth( 300 );
        for( i=0;i<colNum;i++ )
            table1.sizeColumnsToFit(i);

        table1.getTableHeader().setBorder( BorderFactory.createRaisedBevelBorder() );
        table1.getTableHeader().setReorderingAllowed(false);
    }
    
    private void setupServTableForMTPP(){
        int i;
        Object[][] data;

        Vector list = view.initor.mdb.getAllServMapOnClntID( host.getID() );
        int num = list.size();

        data = new Object[2+num][2]; //name,desc
        data[0][0] = "" + num;    // row num
        data[0][1] = "" + 2;      // col num

        data[1][0] = SanBootView.res.getString("SelectServicePane.table.service.name");
        data[1][1] = SanBootView.res.getString("SelectServicePane.table.service.desc");
        
        for( i=0; i<num; i++ ){
            ServiceMap servMap = (ServiceMap)list.elementAt(i);
            
            data[2+i][0] = servMap;
            data[2+i][1] = servMap.getServDesc();
        }

        table1.setTableModel( data );
        table1.setDefaultLook();

        TableColumnModel tableColumnModel = table1.getColumnModel();
        int colNum = tableColumnModel.getColumnCount();
        for( i=0;i<colNum;i++ ){
            tableColumnModel.getColumn(i).setCellRenderer(new BrowserTableCellRenderer());
        }

        tableColumnModel.getColumn(0).setWidth( 150 );
        tableColumnModel.getColumn(1).setWidth( 300 );
        for( i=0;i<colNum;i++ )
            table1.sizeColumnsToFit(i);

        table1.getTableHeader().setBorder( BorderFactory.createRaisedBevelBorder() );
        table1.getTableHeader().setReorderingAllowed(false);
    }
    
    private void setupNetworkInfo(){
        boolean isOk = view.initor.mdb.viewFileContents( ResourceCenter.CLT_IP_CONF + "/" + host.getID() + ".conf" );
        if( isOk ){
            jTextArea1.append( view.initor.mdb.getContentBuf().toString() );
        }else{
            if( host.isInited() ){
                jTextArea1.append( SanBootView.res.getString("HostPropertyDialog.error.getNetworkInfo"));
            }
        }
    }
    
    private void setupPartitionInfo(){
        boolean isOk = view.initor.mdb.viewFileContents( ResourceCenter.CLT_IP_CONF + "/" + host.getID() + "-disk.conf" );
        if( isOk ){
            jTextArea2.append( view.initor.mdb.getContentBuf().toString() );
        }else{
            if( host.isInited() ){
                jTextArea2.append( SanBootView.res.getString("HostPropertyDialog.error.getPartitionInfo"));
            }
        }
    }
}
